export enum MacroMode {
	THE_NUMBER_OF_TIME_TO_PLAY = 0x00,
	ANY_KEY_PRESS_TO_STOP_PLAYING = 0x01,
	PRESS_AND_HOLD_RELEASE_STOP = 0x02,
}

export enum CUSTOM_MACRO_BUTTONS {
	LEFT_BUTTON = 0x01,
	RIGHT_BUTTON = 0x02,
	MIDDLE_BUTTON = 0x03,
	EXTRA_BUTTON_4 = 0x07,
	EXTRA_BUTTON_5 = 0x08,
}
